In [1]:
#importing the librarires
import numpy as np 
import  pandas as pd


In [2]:
pwd #to check the working directory

'/home/neelesh/Desktop/Machine Learning A-Z New/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)'

In [3]:
df=pd.read_csv("Churn_Modelling.csv")

In [4]:
#showing the first ten rows of the dataset
df.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [5]:
#checking the number of columns
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
#checking the number of rows and columns
df.shape

(10000, 14)

# We have 10000 Rows and 14 Columns


In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

# Checking For Null Missing Values

In [8]:

df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# Checking the number of male and female who has exited the Bank


In [9]:
df.groupby("Gender")["Exited"].sum()

Gender
Female    1139
Male       898
Name: Exited, dtype: int64

# Showing the total number of customers Country Wise

In [10]:
df.groupby(["Geography"])["Exited"].count()

Geography
France     5014
Germany    2509
Spain      2477
Name: Exited, dtype: int64

# Showing the Customers of France Who have exited the bank

In [11]:
df[df["Geography"]=="France"]["Exited"].sum()

810

In [12]:
Ratio1=df[df["Geography"]=="France"]["Exited"].sum()/df[df["Geography"]=="France"]["Exited"].count()
print(Ratio1)

0.16154766653370561


# We Can See that about 16% have leave the bank

In [13]:
Ratio2=df[df["Geography"]=="Germany"]["Exited"].sum()/df[df["Geography"]=="Germany"]["Exited"].count()
print(Ratio2)

0.32443204463929853


In [14]:
Ratio3=df[df["Geography"]=="Spain"]["Exited"].sum()/df[df["Geography"]=="Spain"]["Exited"].count()
print(Ratio3)

0.1667339523617279


# We Can See that about 33% customers of Germany have left the Bank

In [15]:
#showing the people
df.groupby("HasCrCard")["HasCrCard"].count()


HasCrCard
0    2945
1    7055
Name: HasCrCard, dtype: int64

In [16]:
df.groupby("HasCrCard")["Exited"].sum()


HasCrCard
0     613
1    1424
Name: Exited, dtype: int64

# WE Have Anlysed Our Data Let's Print Correlation Matrix

In [17]:
df.corr()

RowNumber  CustomerId  CreditScore       Age    Tenure  \
RowNumber         1.000000    0.004202     0.005840  0.000783 -0.006495   
CustomerId        0.004202    1.000000     0.005308  0.009497 -0.014883   
CreditScore       0.005840    0.005308     1.000000 -0.003965  0.000842   
Age               0.000783    0.009497    -0.003965  1.000000 -0.009997   
Tenure           -0.006495   -0.014883     0.000842 -0.009997  1.000000   
Balance          -0.009067   -0.012419     0.006268  0.028308 -0.012254   
NumOfProducts     0.007246    0.016972     0.012238 -0.030680  0.013444   
HasCrCard         0.000599   -0.014025    -0.005458 -0.011721  0.022583   
IsActiveMember    0.012044    0.001665     0.025651  0.085472 -0.028362   
EstimatedSalary  -0.005988    0.015271    -0.001384 -0.007201  0.007784   
Exited           -0.016571   -0.006248    -0.027094  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber       -0.009067       0.007246   0.000599        0.012044   
CustomerId      -0.012419       0.016972  -0.014025        0.001665   
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
RowNumber              -0.005988 -0.016571  
CustomerId              0.015271 -0.006248  
CreditScore            -0.001384 -0.027094  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

In [18]:
#defining the X_set
X=df.iloc[:,3:-1].values


In [19]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
len(X[0])

10

In [21]:
#We Can See that we have two categorical Columns
print(X[:,1:3])

[['France' 'Female']
 ['Spain' 'Female']
 ['France' 'Female']
 ...
 ['France' 'Female']
 ['Germany' 'Male']
 ['France' 'Female']]


In [22]:
#two categotrical values
#we have to encode them
#Making two objecs of LableEncoder Class
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
lb1=LabelEncoder()
lb2=LabelEncoder()


In [23]:
#created two objects of LabelEncoder because we have two categorical values
X[:,1]=lb1.fit_transform(X[:,1])

In [24]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [25]:
X[:,2]=lb2.fit_transform(X[:,2])

In [26]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [27]:
#applying one hotencoding because we have more than two categories in the country column
one_hot=OneHotEncoder(categorical_features=[1])

In [28]:
X=one_hot.fit_transform(X).toarray()

/home/neelesh/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/neelesh/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [29]:
X


array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [30]:
len(X[0])
# we have two more columns because of those two more more countries that we have onehotencoded

12

In [31]:
# to overcome the dummyvariable trap
X=X[:,1:]


In [32]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [33]:
len(X[0])

11

In [34]:
y=df.iloc[:,-1].values

# Splitting the Dataset to train and test 

In [35]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.2)

# Here I Have keep the test_size=0.2
# meaning the 20% will be test set and 80% training set
#random_state so that it will keep that state,meaning on recompling
#weights wont change

In [36]:
#we have preprocessed the data 
#now its time to apply the algorithms
import tensorflow 

# We Are Using Tensorflow

In [37]:
import keras

Using TensorFlow backend.


In [38]:
#For Defining the Layers
from tensorflow.keras.layers import Dense

In [39]:
#For Defining the Model
from tensorflow.keras.models import Sequential

In [40]:
#Created An Object of Model
regressor=Sequential()

# Defining The Layers

In [41]:
regressor.add(Dense(units=6,input_shape=(11,), activation='relu'))
#units means the Neurons on the Outer(Here Hidden Layer)

In [42]:
regressor.add(Dense(units=6,activation='relu'))
#We need not to define the input_shape here because the now it is known 
#to the layer as it will be accepting 6 outputs from the Previous Layer

In [43]:
regressor.add(Dense(units=1,activation='sigmoid'))
#output Layer as Binary output so using Activation Function as sigmoid

In [44]:
regressor.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [45]:

regressor.fit(X_train,y_train,batch_size=32,epochs=25)

Train on 8000 samples
Epoch 1/25
8000/8000 [==============================] - 2s 268us/sample - loss: 18056.0557 - accuracy: 0.3609
Epoch 2/25
8000/8000 [==============================] - 1s 74us/sample - loss: 454.3707 - accuracy: 0.5325
Epoch 3/25
8000/8000 [==============================] - 1s 74us/sample - loss: 31.2001 - accuracy: 0.7041
Epoch 4/25
8000/8000 [==============================] - 1s 74us/sample - loss: 27.9154 - accuracy: 0.7042
Epoch 5/25
8000/8000 [==============================] - 1s 85us/sample - loss: 28.2608 - accuracy: 0.7114
Epoch 6/25
8000/8000 [==============================] - 1s 120us/sample - loss: 16.3092 - accuracy: 0.7099
Epoch 7/25
8000/8000 [==============================] - 1s 102us/sample - loss: 18.1775 - accuracy: 0.7120
Epoch 8/25
8000/8000 [==============================] - 1s 90us/sample - loss: 20.3923 - accuracy: 0.7103
Epoch 9/25
8000/8000 [==============================] - 1s 93us/sample - loss: 21.2891 - accuracy: 0.7191
Epoch 10/25
8000/

#  We can see that we have achieved accuracy 72% in 25 epochs

In [46]:
def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(units=6,activation='relu',input_dim=11))
    
    classifier.add(Dense(units=6,activation='relu'))
    
    classifier.add(Dense(units=1,activation='sigmoid'))
    
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier
                   

In [57]:
y_pred=regressor.predict(X_test)
y_pred=(y_pred>0.5)
print(y_pred)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]
[[1595    0]
 [ 404    1]]


In [58]:
from keras.wrappers.scikit_learn import KerasClassifier
classifier=KerasClassifier(build_fn=build_classifier)

In [59]:

from sklearn.model_selection import GridSearchCV
parameters = {'epochs': [ 50,100], 'batch_size': [16,32]}
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)

grid_search = grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 1s 115us/sample - loss: 3775.8726 - accuracy: 0.7295
Epoch 2/100
8000/8000 [==============================] - 0s 61us/sample - loss: 634.9242 - accuracy: 0.6432
Epoch 3/100
8000/8000 [==============================] - 0s 61us/sample - loss: 211.1985 - accuracy: 0.6466
Epoch 4/100
8000/8000 [==============================] - 0s 60us/sample - loss: 68.7319 - accuracy: 0.6689
Epoch 5/100
8000/8000 [==============================] - 0s 61us/sample - loss: 23.2057 - accuracy: 0.6799
Epoch 6/100
8000/8000 [==============================] - 0s 61us/sample - loss: 14.8912 - accuracy: 0.6823
Epoch 7/100
8000/8000 [==============================] - 0s 62us/sample - loss: 9.8039 - accuracy: 0.6873
Epoch 8/100
8000/8000 [==============================] - 0s 58us/sample - loss: 10.6562 - accuracy: 0.6904
Epoch 9/100
8000/8000 [==============================] - 0s 62us/sample - loss: 11.8045 - accuracy: 0.6808
Epoch 10/10

8000/8000 [==============================] - 1s 63us/sample - loss: 0.5060 - accuracy: 0.7960
Epoch 78/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.5059 - accuracy: 0.7960
Epoch 79/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.5060 - accuracy: 0.7960
Epoch 80/100
8000/8000 [==============================] - 1s 66us/sample - loss: 0.5059 - accuracy: 0.7960
Epoch 81/100
8000/8000 [==============================] - 0s 59us/sample - loss: 0.5059 - accuracy: 0.7960
Epoch 82/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.5060 - accuracy: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 78us/sample - loss: 0.5060 - accuracy: 0.7960
Epoch 84/100
8000/8000 [==============================] - 0s 62us/sample - loss: 0.5059 - accuracy: 0.7960
Epoch 85/100
8000/8000 [==============================] - 0s 59us/sample - loss: 0.5060 - accuracy: 0.7960
Epoch 86/100
8000/8000 [==========================

In [60]:
best_accuracy

0.771875

In [61]:
best_parameters

{'batch_size': 32, 'epochs': 100}